### ISSUE TITLE
Repeated attempts to refactor don't lead to commit messages being pre-popluated

### ISSUE THREAD

**Issue by emilybache** [nymann/commit-refactoring#14]
I've been trying to get this plugin to work because it has functionality I'd really like to have - thankyou so much for creating it!

However I havn't been successful. Thanks for responding to my review and pointing me to where I should add my feedback instead.

I got it to produce a commit message once and I can't seem to reproduce what it is I did to trigger that. I've tried various combinations of re-starting the IDE, opening and closing the commit dialog, using undo, various different refactorings. 

I'm using a recent version of IntelliJ - 2024.1.4 - and I'm trying 'extract method' and 'extract variable'. I havn't made any commits, I just do a refactoring, open the commit dialog and, when there is no message, undo and try a different refactoring. Still no message. Does it matter if the commit dialog is open or closed? Does it matter which refactoring I do? Does it matter that I don't actually commit anything?

I look forward to updates to this plugin and/or instructions on what to do to trigger it.

**Comment by kristian-jakobsen** [comment]
Hey @emilybache 

I've been a bit to eager to share it with the world before it was in a more ready state. So thank you for your continued feedback.

I'm personally using IntelliJ IDEA Ultimate 2024.2

I'm suspecting you are writing Java? (other languages should work too however the commit messages are far from ideal)

It seems like it's not working using the non-modal editor.

# To reproduce

## IntelliJ IDEA Community Edition 2024.2  (Not working)
1. Fresh community edition IntelliJ install.
2. Create new Java project with sample code:
![image](https://github.com/user-attachments/assets/9bc0f72f-7fbb-418f-a903-4df04d0b9bb3)
3. Install the plugin from the Market place (no restart is required)
![image](https://github.com/user-attachments/assets/fb9b849d-e461-4ed4-be87-a49b25b581ff)
4. Make a commit with the sample code:
![image](https://github.com/user-attachments/assets/3bf2a6f0-b481-4385-a983-05cb040e6a0c)

6. Do a refactoring:
![image](https://github.com/user-attachments/assets/b2865a6d-583c-42a0-ba23-2f75f539d953)

7. Commit message doesn't get filled
![image](https://github.com/user-attachments/assets/e4244bd6-8c9b-4c7b-8eb9-cd8ecce0427e)

At this point it should work, but a funny observation on top of that, is that if you commit those changes.
![image](https://github.com/user-attachments/assets/d2c2fe46-0ec3-41d6-b3a6-f021b21080d1)

![image](https://github.com/user-attachments/assets/6c2ea428-2a85-4dec-a8be-6ada8fee876e)
It fills in the message afterwards.

To me this seems like the bug has to due with the Community Version of the VCS.

## IntelliJ IDEA Ultimate Edition 2024.2 (Works Using Modal Commit viewer)

In the Ultimate version:
1. 
![image](https://github.com/user-attachments/assets/88cddc02-067f-4c0d-9d57-9a11bd38f357)
2. 
![image](https://github.com/user-attachments/assets/8b189ec3-fdd0-4627-9199-33f72d4c4d4d)
3. Extract method
![image](https://github.com/user-attachments/assets/4d56f8c0-942e-4c34-92f9-20b9b4a04b7e)
4. Open the modal commit window (Command + K)
![image](https://github.com/user-attachments/assets/9406267d-43a2-47a8-be00-076b5ac8dcc1)

## IntelliJ IDEA Ultimate Edition 2024.2 (Not working Using Default Commit viewer)
1. Switch to non modal viewer
![image](https://github.com/user-attachments/assets/0f618fc5-6f07-45ed-9f0a-10cd059c4573)
2. Do a refactoring.
3. Commit message stays the same.
4. Same as with the community edition, the commit message then gets updated afterwards.

**Comment by emilybache** [comment]
I've been using IDEA Ultimate and I havn't used the modal commit dialog at all. What I'm seeing now is that the commit messages show up after I already made a commit. They are piling up actually. I do a lot of refactorings then stash or undo them. They are just piling up in a list that appears after I commit!

**Comment by nymann** [comment]
> I've been using IDEA Ultimate and I havn't used the modal commit dialog at all. What I'm seeing now is that the commit messages show up after I already made a commit. They are piling up actually. I do a lot of refactorings then stash or undo them. They are just piling up in a list that appears after I commit!

Hey Emily, yes it's only the modal editor that works. The non-modal editor (the one you are using) is currently not supported. I've opened #25 to fix this

**Comment by nymann** [comment]
0.1.5 have just been approved by JetBrains, it includes (among other things) a fix this problem @emilybache 

If you are experiencing any further issues, or have suggestions to improvements, please open a new issue 🚀
