### ISSUE TITLE
Add support for non-modal editor

### ISSUE THREAD

**Issue by nymann** [nymann/commit-refactoring#25]

**Comment by nymann** [comment]
Update: I started adding a UI test to showcase the problem.

**Comment by nymann** [comment]
![image](https://github.com/user-attachments/assets/7a2079e1-e984-4c13-8f19-59ebc11ad56b)

Added support for updating the commit message via the button for non-modal users in https://github.com/nymann/commit-refactoring/commit/8705709340ff7e4f96ba731adf4990ca8ee538bb

**Comment by nymann** [comment]
Added in https://github.com/nymann/commit-refactoring/commit/c38436c8502c6a306bffecefa49e8086565a5d86

**Comment by nymann** [comment]
Released in 0.1.3 waiting for JetBrains approval

**Comment by felixthegit** [comment]
Amazing
