### ISSUE TITLE
Commit message "UNSAFE"

### ISSUE THREAD

**Issue by felixthegit** [nymann/commit-refactoring#47]
In my TypeScript project the commit message is reset to "UNSAFE" if I did no refactoring since last commit.
In such a case the commit message should not be set by the plugin and keep the last message

**Comment by nymann** [comment]
> In my TypeScript project the commit message is reset to "UNSAFE" if I did no refactoring since last commit. In such a case the commit message should not be set by the plugin and keep the last message

Hey Felix,
If you are using version 0.1.6 you can go into the commit refactoring settings and remove everything in the Default message field:

<img width="327" alt="image" src="https://github.com/user-attachments/assets/fe222849-e8b7-4483-ac2b-f3f497c8aea9">


I personally quite like that I receive a different message when I'm in the habit of "see refactoring commit message, auto accept" :-)

**Comment by felixthegit** [comment]
Ah thanks! I haven't seen this new option.
What is the meaning of "UNSAFE" as default?

**Comment by nymann** [comment]
> Ah thanks! I haven't seen this new option. What is the meaning of "UNSAFE" as default?
Just to prevent accidentally committing with the last refactoring message when no refactoring have been done

**Comment by felixthegit** [comment]
That makes sense :D

Maybe you could evaluate the ${placeholder} in the default message, too, so that I can have my "${branch}: " prefix there

**Comment by kristian-jakobsen** [comment]
> That makes sense :D
> 
> Maybe you could evaluate the ${placeholder} in the default message, too, so that I can have my "${branch}: " prefix there

oh, good idea

**Comment by nymann** [comment]
> That makes sense :D
> 
> Maybe you could evaluate the ${placeholder} in the default message, too, so that I can have my "${branch}: " prefix there

Great idea. Feel free to do a PR 😄

**Comment by felixthegit** [comment]
Here it is: https://github.com/nymann/commit-refactoring/pull/48
